version: "2"
services:
        orthanc:
                build: orthanc
                depends_on: [orthanc-index]
                restart: unless-stopped
                #ports: ["104:4242", "8042:8042"]
                ports: ["8042:8042"]
                volumes: ["/mnt/disks/orthanc-db/storage:/var/lib/orthanc/db:Z"]

                environment:
		    #Enable Web Viewer plugin
                    - WVB_ENABLED=true
		    # Enable Postgresql plugin
                    - PG_ENABLED=true
		    # Enable DICOMweb plugin
                    - DW_ENABLED=true
#                    - TRACE_ENABLED=true
#                    - VERBOSE_ENABLED=true

        orthanc-index:
                image: postgres
                restart: unless-stopped
#                volumes: ["/mnt/disks/orthanc-index/postgresql/data:/var/lib/postgresql/data:Z"]
                volumes: ["/var/lib/postgresql/data:/var/lib/postgresql/data:Z"]
