version: "2"
services:
        orthanc:
                build: orthanc
                depends_on: [orthanc-index]
                restart: unless-stopped
                #ports: ["104:4242", "8042:8042"]
                ports: ["8042:8042"]
                volumes: ["/mnt/disks/orthanc-db/storage:/var/lib/orthanc/db:Z"]

                environment:
                    - WVB_ENABLED=true
                    - PG_ENABLED=true
#                    - TRACE_ENABLED=true
#                    - VERBOSE_ENABLED=true

        orthanc-index:
                image: postgres:10.4
                restart: unless-stopped
                volumes: ["/mnt/disks/orthanc-index/postgresql/data:/var/lib/postgresql/data:Z"]
